provider, hostname-operator: fix comparison type issue (#140)
Either one --set beta=true or  --set beta="true" causes these issues:

Error: UPGRADE FAILED: template: provider/templates/deployment.yaml:1:7: executing "provider/templates/deployment.yaml" at <eq .Values.beta "false">: error calling eq: incompatible types for comparison

Error: UPGRADE FAILED: template: akash-hostname-operator/templates/deployment.yaml:34:7: executing "akash-hostname-operator/templates/deployment.yaml" at <eq .Values.beta "false">: error calling eq: incompatible types for comparison